In [2]:
#Task 1
def convert_length(value, from_unit, to_unit):
  length_units = {
      "meters": 1, "kilometers" : 0.001 , "miles" : 0.000621371 , "feet" : 3.28084, "inches" : 39.3701
  } 
  if from_unit in length_units and to_unit in length_units:
    return value * (length_units[to_unit]/length_units[from_unit])
  else: 
    return None 

def convert_weight(value, from_unit, to_unit):
  weight_units = {
      "grams" : 1 , "kilograms" : 0.001 , "pounds" : 0.00220462 , "ounces" : 0.035724
  }
  if from_unit in weight_units and to_unit in weight_units:
    return value * (weight_units[from_unit] / weight_units[from_unit])
  else:
    return None 

def convert_volume(value , from_unit, to_unit):
  volume_units = {
      "litres":1 , "millilitres" : 1000, "gallons" : 0.264172, "cups" : 4.22675 
  }
  if from_unit in volume_units and to_unit in volume_units:
    return value * volume_units[from_unit]/volume_units[to_unit]
  else: 
    return None 

def main():
  print("Welcome to the unit converter")
  print("Choose a conversion type: Length, weight, volume")
  conversion_type = input("Enter conversion type: ").strip().lower()
  if conversion_type not in ["length","weight", "volume"]:
    print("Invalid Conversion Type.Please enter 'length','weight','volume'")
    return

  try:
    value = float(input("Enter the value to convert:"))
  except ValueError:
    print("Invalid Input. Please enter a numerical value.")
    return

  from_unit = input("Enter the unit you are converting from : ").strip().lower()
  to_unit = input("Enter the unit you are converting to:").strip().lower()

  if conversion_type == "length":
    result = convert_length(value, from_unit, to_unit)
  elif conversion_type == "weight":
    result = convert_weight(value, from_unit, to_unit)
  elif conversion_type == "volume":
    result = convert_length(value, from_unit, to_unit)
  else:
     result = None 

  if result is not None:
    print(f"{value} {from_unit} is equal to {result:.4f} {to_unit}")

  else: 
    print("Invalid unit selection. Please check your unit inputs.")

if __name__ == "__main__":
  main()

Welcome to the unit converter
Choose a conversion type: Length, weight, volume
4.0 kilometers is equal to 4000.0000 meters


In [24]:
#Task 2
def calculate_sum(numbers):
  return sum(numbers)

def calculate_average(numbers):
  return sum(numbers) / len(numbers) if numbers else None

def find_maximum(numbers):
  return max(numbers)

def find_minimum(numbers):
  return min(numbers)

def main(): 
  print("Welcome to the Math Operation Program")
  print("Choose an operation: Sum,Average,Max, Min")
  operation = input("Please enter the operation").strip().lower()
  if operation not in ["sum",'average', 'max', 'min']:
    print("Please enter a valid operation")
    return
  numbers_input = input("Please enter the list of numbers seperated by spaces.").strip()
  try: 
    numbers = [float(num) for num in numbers_input.split()]
    if not numbers:
      raise ValueError("List is empty")
  except ValueError:
      print("Please enter a valid list of numbers")
      return 
  
  if operation == "sum":
    result = calculate_sum(numbers)
  elif operation == "average":
    result = calculate_average(numbers)
  elif operation == "max":
    result = find_maximum(numbers)
  elif operation == "min":
    result = find_minimum(numbers)
  else:
    result = None
  
  if result is not None :
    print(f"The result of {operation} operation is : {result}")

  else:
    print("Could not perform the operation")

if __name__ == "__main__":
  main()
  


Welcome to the Math Operation Program
Choose an operation: Sum,Average,Max, Min
The result of sum operation is : 6.0


In [4]:
#Exercise 4.1 Task 1
def extract_every_other(lst):
  return lst[::2]

input_list = [1,2,3,4,5,6]
output_list = extract_every_other(input_list)
print("Original List:", input_list)
print("Output List:", output_list)


Original List: [1, 2, 3, 4, 5, 6]
Output List: [1, 3, 5]


In [5]:
#Exercise 4.1 Task 2
def get_sublist(lst, start, end):
  return lst[start:end + 1]

input_list = [1,2,3,4,5,6]
start_index = 2
end_index = 4

output_list = get_sublist(input_list, start_index, end_index)
print(f"The sublist of the above list {input_list} is \n{output_list}")

The sublist of the above list [1, 2, 3, 4, 5, 6] is 
[3, 4, 5]


In [6]:
#Exercise 4.2 Task 3
def reverse_list(lst):
  return lst[::-1]

input_list = [1,2,3,4,5]
output_list = reverse_list(input_list)
print("The reversed list is \n",output_list)

The reversed list is 
 [5, 4, 3, 2, 1]


In [7]:
#Exercise 4.2 Task 4
def remove_first_last(lst):
  return lst[1:-1]

input_list = [1,2,3,4,5,6,7]
output_list = remove_first_last(input_list)
print("The list after removing the first and last elements is: ", output_list)

The list after removing the first and last elements is:  [2, 3, 4, 5, 6]


In [8]:
#Exercise 4.2 Task 5
def get_first_n(lst,n):
  return lst[:n]

input_list = [1,2,3,4,5]
n = 3 
output_list = get_first_n(input_list,n)
print(f"The list till the index {n} is \n {output_list}")

The list till the index 3 is 
 [1, 2, 3]


In [9]:
#Exercise 4.2 Task 6
def get_last_n(lst,n):
  return lst[-n:]
 
input_list = [1,2,3,4,5]
n = 2 
output_list = get_last_n(input_list,n)
print(f"The extracted list is {output_list}")

The extracted list is [4, 5]


In [10]:
#Exercise 4.2 Task 7
def reverse_skip(lst):
  return lst[-2::-2]

input_list = [1,2,3,4,5,6]
output_list = reverse_skip(input_list)
print("The new list is ", output_list)

The new list is  [5, 3, 1]


In [11]:
#Exercise 4.3 Task 1
def flatten(lst):
  flat_list = []
  for item in lst:
    if isinstance(item,list):
      flat_list.extend(flatten(item))
    else: 
      flat_list.append(item)
  return flat_list

input_list = [[1,2],[3,4],[5]]
print(flatten(input_list))

[1, 2, 3, 4, 5]


In [12]:
#Exercise 4.3 Task 2
def access_nested_element(lst, indices):
  element = lst 
  for index in indices:
    element = element[index]
  return element

nested_list = [[1,2,3],[4,5,6],[7,8,9]]
indices = [1,2]
print(access_nested_element(nested_list, indices))

6


In [13]:
#Exercise 4.3 Task 3
def sum_nested(lst):
  total = 0
  for item in lst:
    if isinstance(item,list):
      total += sum_nested(item)
    else:
      total += item
  return total

input_list = [[1,2],[3,[4,5]],6]
print(sum_nested(input_list))

21


In [14]:
#Exercise 4.3 Task 4
def remove_element(lst, elem):
  result = []
  for item in lst:
    if isinstance(item,list):
      filtered_sublist = remove_element(item,elem)
      if filtered_sublist:
        result.append(filtered_sublist)
    elif item != elem:
      result.append(item)
  return result

input_list = [[1,2],[3,2],[4,5]]
print(remove_element(input_list,2))
  

[[1], [3], [4, 5]]


In [15]:
#Exercise 4.3 Task 5
def find_max(lst):
  max_value = float('-inf')
  for item in lst: 
    if isinstance(item,list):
      max_value = max(max_value, find_max(item))
    else: 
      max_value = max(max_value, item)
  return max_value

input_list = [[1,2],[3,[4,5]],[6]]
print(find_max(input_list))
    

6


In [16]:
#Exercise 4.3 Task 6
def count_occurences(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item, list): 
      count += count_occurences(item, elem)
    elif item == elem:
      count += 1
  return count 

input_list = [[1,2],[2,3],[2,4]]
print(count_occurences(input_list,2))

3


In [17]:
#Exercise 4.3 Task 7
def deep_flatten(lst):
  flat_list = []
  for item in lst:
    if isinstance(item, list):
      flat_list.extend(deep_flatten(item))
    else: 
      flat_list.append(item)
  return flat_list

input_list = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(deep_flatten(input_list))

[1, 2, 3, 4, 5, 6, 7, 8]


In [18]:
#Exercise 4.3 Task 8
def average_nested(lst):
  flattened = deep_flatten(lst)
  return sum(flattened) / len(flattened) if flattened else 0

input_list = [[1,2],[3,4],[5,6]]
print(average_nested(input_list))

3.5


In [19]:
#Problem 1
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("Ones Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with a value
filled_array = np.full((3, 3), 7)
print("Filled Array:\n", filled_array)

# 4. Return a new zero array with the same shape and type as another array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zero_like_array = np.zeros_like(reference_array)
print("Zeros Like:\n", zero_like_array)

# 5. Return a new ones array with the same shape and type as another array
ones_like_array = np.ones_like(reference_array)
print("Ones Like:\n", ones_like_array)

# 6. Convert a Python list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array:", numpy_array)

Empty Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like:
 [[0 0 0]
 [0 0 0]]
Ones Like:
 [[1 1 1]
 [1 1 1]]
Converted NumPy Array: [1 2 3 4]


In [20]:
#Problem 2
# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Range Array:", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find its mean
random_array = np.random.random(30)
print("Mean of Random Array:", random_array.mean())

# 5. Create a 10x10 array with random values and find min & max
random_matrix = np.random.random((10, 10))
print("Min:", random_matrix.min(), "Max:", random_matrix.max())

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Modified Zero Array:", zero_array)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

# 8. Create a 2D array with 1s on the border and 0s inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("Bordered Array:\n", border_array)

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:\n", checkerboard)

Range Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of Random Array: 0.5225163759784468
Min: 0.0039564574201319536 Max: 0.9919509002191695
Modified Zero Array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array: [0 4 0 0 2 1]
Bordered Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [21]:
#Problem 3
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Addition
add_result = x + y
print("Addition:\n", add_result)

# 2. Subtraction
sub_result = x - y
print("Subtraction:\n", sub_result)

# 3. Multiply with an integer
mult_result = x * 3
print("Multiplied:\n", mult_result)

# 4. Square each element
square_result = np.square(x)
print("Squared:\n", square_result)

# 5. Dot Product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot Product (v & w):", dot_vw)
print("Dot Product (x & v):", dot_xv)
print("Dot Product (x & y):\n", dot_xy)

# 6. Concatenation
concat_x_y = np.concatenate((x, y), axis=0)
concat_v_w = np.vstack((v, w))
print("Concatenation (x & y):\n", concat_x_y)
print("Concatenation (v & w):\n", concat_v_w)

# 7. Concatenating x & v (Error Explanation)
try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error:", e)  # Shapes mismatch: Cannot concatenate 2D and 1D arrays

Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiplied:
 [[ 3  6]
 [ 9 15]]
Squared:
 [[ 1  4]
 [ 9 25]]
Dot Product (v & w): 219
Dot Product (x & v): [29 77]
Dot Product (x & y):
 [[19 22]
 [50 58]]
Concatenation (x & y):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation (v & w):
 [[ 9 10]
 [11 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [22]:
#Problem 4
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A⁻¹:\n", identity)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA))  # Should be False

# 3. Prove (AB)ᵀ = Bᵀ Aᵀ
transpose_AB = np.transpose(AB)
transpose_BA = np.dot(np.transpose(B), np.transpose(A))
print("(AB)ᵀ:\n", transpose_AB)
print("Bᵀ Aᵀ:\n", transpose_BA)
print("(AB)ᵀ == Bᵀ Aᵀ?", np.array_equal(transpose_AB, transpose_BA))  # Should be True

# Solve system of equations using inverse method
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

X_solution = np.linalg.solve(A_matrix, B_matrix)
print("Solution for system of equations:", X_solution)

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False
(AB)ᵀ:
 [[23 51]
 [13 29]]
Bᵀ Aᵀ:
 [[23 51]
 [13 29]]
(AB)ᵀ == Bᵀ Aᵀ? True
Solution for system of equations: [ 2.  1. -2.]


In [23]:
#Exercise 10.2
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)

# 1. Element-wise Addition
start = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python List Addition Time:", end - start)

start = time.time()
result_array = array1 + array2
end = time.time()
print("NumPy Array Addition Time:", end - start)

# 2. Element-wise Multiplication
start = time.time()
result_list = [x * y for x, y in zip(list1, list2)]
end = time.time()
print("Python List Multiplication Time:", end - start)

start = time.time()
result_array = array1 * array2
end = time.time()
print("NumPy Array Multiplication Time:", end - start)

# 3. Dot Product
start = time.time()
dot_list = sum(x * y for x, y in zip(list1, list2))
end = time.time()
print("Python List Dot Product Time:", end - start)

start = time.time()
dot_array = np.dot(array1, array2)
end = time.time()
print("NumPy Array Dot Product Time:", end - start)

Python List Addition Time: 0.040947914123535156
NumPy Array Addition Time: 0.0022919178009033203
Python List Multiplication Time: 0.04860496520996094
NumPy Array Multiplication Time: 0.0015211105346679688
Python List Dot Product Time: 0.06514596939086914
NumPy Array Dot Product Time: 0.0006687641143798828
